/**
 * PR Summary Comment generator.
 * Aggregates test results, bundle size diff, and lint/type-check status
 * into a single PR comment. Updates existing bot comment to avoid spam.
 */
import { execSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { createCiLogger } from './logger.js'

const logger = createCiLogger('pr-summary')
const ROOT = resolve(import.meta.dirname, '../..')

type JobStatus = 'pass' | 'fail' | 'skip'

interface JobResult {
  name: string
  status: JobStatus
}

const STATUS_EMOJI: Record<JobStatus, string> = { pass: '✅', fail: '❌', skip: '⏭️' }
const BOT_COMMENT_MARKER = 'Generated by CI pipeline'

function collectJobResults(): JobResult[] {
  return [
    { name: 'Lint + Type Check', status: (process.env.LINT_STATUS as JobStatus) ?? 'skip' },
    { name: 'Build', status: (process.env.BUILD_STATUS as JobStatus) ?? 'skip' },
    { name: 'Build Validation', status: (process.env.VALIDATE_STATUS as JobStatus) ?? 'skip' },
    { name: 'Unit + Integration Tests', status: (process.env.TEST_STATUS as JobStatus) ?? 'skip' },
    { name: 'Cypress Component Tests', status: (process.env.E2E_STATUS as JobStatus) ?? 'skip' },
    { name: 'Compat (Latest)', status: (process.env.COMPAT_LATEST_STATUS as JobStatus) ?? 'skip' },
    { name: 'Compat (Minimum)', status: (process.env.COMPAT_MIN_STATUS as JobStatus) ?? 'skip' },
    { name: 'Security Gate', status: (process.env.SECURITY_STATUS as JobStatus) ?? 'skip' },
    { name: 'Docs Build', status: (process.env.DOCS_STATUS as JobStatus) ?? 'skip' },
  ]
}

function buildJobsTable(jobs: JobResult[]): string {
  let md = '| Check | Status |\n'
  md += '|-------|--------|\n'
  for (const job of jobs) {
    md += `| ${job.name} | ${STATUS_EMOJI[job.status]} ${job.status.toUpperCase()} |\n`
  }
  return md
}

function buildComment(): string {
  const prNumber = process.env.PR_NUMBER ?? 'unknown'
  const commitSha = (process.env.COMMIT_SHA ?? 'unknown').slice(0, 7)
  const jobs = collectJobResults()
  const allPassed = jobs.every((j) => j.status === 'pass' || j.status === 'skip')

  let md = `## ${allPassed ? '✅' : '❌'} PR Check Summary\n\n`
  md += `**Commit:** \`${commitSha}\` | **PR:** #${prNumber}\n\n`
  md += buildJobsTable(jobs)

  // Bundle size diff
  const sizeDiffPath = resolve(ROOT, 'size-diff.md')
  if (existsSync(sizeDiffPath)) {
    md += '\n---\n\n'
    md += readFileSync(sizeDiffPath, 'utf-8')
  }

  // Test coverage summary
  const coverageSummary = process.env.COVERAGE_SUMMARY
  if (coverageSummary) {
    md += '\n---\n\n### Test Coverage\n\n'
    md += coverageSummary
  }

  // Preview links
  md += '\n---\n\n### Preview\n\n'

  const docsPreviewUrl = process.env.DOCS_PREVIEW_URL
  if (docsPreviewUrl) {
    md += `- [Docs Preview](${docsPreviewUrl})\n`
  }

  const pkgPreviewInfo = process.env.PKG_PREVIEW_INFO
  if (pkgPreviewInfo) {
    md += `- **Package Preview (pkg-pr-new):**\n${pkgPreviewInfo}\n`
  }

  md += `\n---\n*${BOT_COMMENT_MARKER}*\n`

  return md
}

function findExistingCommentId(repo: string, prNumber: string, token: string): string | null {
  try {
    const result = execSync(
      `gh api repos/${repo}/issues/${prNumber}/comments --jq '[.[] | select(.body | contains("${BOT_COMMENT_MARKER}")) | .id] | first // empty'`,
      { encoding: 'utf-8', env: { ...process.env, GH_TOKEN: token } },
    ).trim()
    return result || null
  } catch {
    // gh CLI failure -- no existing comment found
    return null
  }
}

function postOrUpdateComment(repo: string, prNumber: string, token: string, comment: string): void {
  const existingId = findExistingCommentId(repo, prNumber, token)
  const escapedComment = comment.replace(/'/g, "'\\''")

  if (existingId) {
    execSync(
      `gh api repos/${repo}/issues/comments/${existingId} -X PATCH -f body='${escapedComment}'`,
      { stdio: 'inherit', env: { ...process.env, GH_TOKEN: token } },
    )
    logger.info(`Updated existing comment ${existingId}`)
  } else {
    execSync(`gh api repos/${repo}/issues/${prNumber}/comments -f body='${escapedComment}'`, {
      stdio: 'inherit',
      env: { ...process.env, GH_TOKEN: token },
    })
    logger.info('Created new PR comment')
  }
}

async function main(): Promise<void> {
  const comment = buildComment()
  const prNumber = process.env.PR_NUMBER
  const repo = process.env.GITHUB_REPOSITORY
  const token = process.env.GITHUB_TOKEN

  if (!prNumber || !repo || !token) {
    logger.warn('Missing PR_NUMBER, GITHUB_REPOSITORY, or GITHUB_TOKEN — printing to stdout')
    logger.info(comment)
    return
  }

  try {
    postOrUpdateComment(repo, prNumber, token, comment)
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error)
    logger.error(`Failed to post PR comment: ${message}`)
    logger.info(comment)
  }
}

main()
